services:
  postgres:
    image: postgres:latest
    container_name: next-app-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container_openai_poc
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8081:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    links:
      - postgres:pgsql-server

volumes:
  postgres_data:
  pgadmin:
